module.exports = [
    {
        id: 4,
        slug: "blog-j80-3000-second-life",
        url: "blog-j80-3000-second-life.html",
        navOrder: 4,
        featured: true,
        image: "images/Cherry_J80-3000_I2C.jpg",
        meta: "Werkstattbericht · Projekt J80-3000",
        date: "22. April 2026",
        datetime: "2026-04-22",
        title: "J80-3000 – einer alten Cherry ein zweites Leben geben",
        excerpt: "Die G80-3000 hat für mich genau das, was viele alte Geräte interessant macht: Sie sieht nach echter Hardware aus und hat Charakter. Gleichzeitig…",
        quote: "Der PC sagt „Tastatur erkannt“. Die Tastatur sagt: „Nö.“",
        imageAlt: "J80-3000 Controller-Swap mit Blackpill und I2C-Expander auf der Werkbank",
        imageTitle: "J80-3000 I2C Setup",
    },
    {
        id: 7,
        slug: "blog-corsair-k70",
        url: "blog-corsair-k70.html",
        navOrder: 7,
        image: "images/Werkbankfoto_1.jpg",
        meta: "Persönlich · Tastaturgeschichte",
        date: "27. Juli 2026",
        datetime: "2026-07-27",
        title: "Wie aus einer Corsair K70 ein Tastatur-Hobby wurde",
        excerpt: "Der Anfang war eigentlich ziemlich banal: Ich hatte eine Corsair K70 Vengeance. Sie war keineswegs eine schlechte Tastatur – aber ich war mit ihr…",
        imageAlt: "Wie aus einer Corsair K70 ein Tastatur-Hobby wurde",
        imageTitle: "Wie aus einer Corsair K70 ein Tastatur-Hobby wurde",
    },
    {
        id: 6,
        slug: "blog-tofu65-v2",
        url: "blog-tofu65-v2.html",
        navOrder: 6,
        image: "images/Tofu65_Brutalis-Keycaps.jpg",
        meta: "Build-Story · Tofu65 2.0",
        date: "19. Juni 2026",
        datetime: "2026-06-19",
        title: "Meine erste eigene Tastatur: die Tofu65 2.0",
        excerpt: "Irgendwann war klar: Lesen reicht nicht mehr. Ich wollte selbst ausprobieren, wie sich verschiedene Komponenten auf eine Tastatur auswirken.",
        imageAlt: "Meine erste eigene Tastatur: die Tofu65 2.0",
        imageTitle: "Meine erste eigene Tastatur: die Tofu65 2.0",
    },
    {
        id: 5,
        slug: "blog-10-euro-ps2-connector",
        url: "blog-10-euro-ps2-connector.html",
        navOrder: 5,
        image: "images/10Euro_PS2.jpg",
        meta: "Fundstück · Cherry G80-3000",
        date: "30. Mai 2026",
        datetime: "2026-05-30",
        title: "10 € und ein PS/2-Stecker",
        excerpt: "Dann kam eine Cherry G80-3000 für gerade einmal 10 €. Bei dem Preis musste ich nicht lange überlegen.",
        imageAlt: "10 € und ein PS/2-Stecker",
        imageTitle: "10 € und ein PS/2-Stecker",
    },
    {
        id: 3,
        slug: "blog-keyboards-for-others",
        url: "blog-keyboards-for-others.html",
        navOrder: 3,
        image: "images/Lucky65_Red.jpg",
        meta: "Hobby · Community",
        date: "15. März 2026",
        datetime: "2026-03-15",
        title: "Der schönste Nebeneffekt: Tastaturen für andere bauen",
        excerpt: "Irgendwann blieb es nicht mehr bei meinen eigenen Tastaturen. Freunde und Bekannte bekamen mit, dass man so eine Tastatur tatsächlich komplett nach…",
        imageAlt: "Der schönste Nebeneffekt: Tastaturen für andere bauen",
        imageTitle: "Der schönste Nebeneffekt: Tastaturen für andere bauen",
    },
    {
        id: 2,
        slug: "blog-old-keyboards",
        url: "blog-old-keyboards.html",
        navOrder: 2,
        image: "images/Cherry_G80-1000_2.jpg",
        meta: "Gedanken · Sammeln & Restaurieren",
        date: "8. Februar 2026",
        datetime: "2026-02-08",
        title: "Warum alte Tastaturen plötzlich interessant werden",
        excerpt: "Seit ich mich intensiver mit Tastaturen beschäftige, sehe ich alte Boards anders. Was früher einfach eine gebrauchte Tastatur war, kann heute ein…",
        imageAlt: "Warum alte Tastaturen plötzlich interessant werden",
        imageTitle: "Warum alte Tastaturen plötzlich interessant werden",
    },
    {
        id: 1,
        slug: "blog-getting-started",
        url: "blog-getting-started.html",
        navOrder: 1,
        image: "images/YMDK68_Wood_workbench.jpg",
        meta: "Auftakt",
        date: "12. Januar 2026",
        datetime: "2026-01-12",
        title: "Beginn von etwas ganz Großem",
        excerpt: "Hier entsteht eine Webseite rund um mechanische Tastaturen – besonders um solche mit deutschem ISO-Layout, eigene Builds, Restaurierungen und die…",
        imageAlt: "Beginn von etwas ganz Großem",
        imageTitle: "Beginn von etwas ganz Großem",
    },
];
